cups-server:
  container_name: canon-cups-docker
  restart: always
  image: stonecan/canon-cups-docker:latest
  ports:
    - "631:631"
  volumes:
    - /var/docker/cups-docker/cupsd.conf:/etc/cups/cupsd.conf
  environment:
    - CUPS_USER_ADMIN=admin
    - CUPS_USER_PASSWORD=secr3t
  devices:
    - "${PRINTER_ADDRESS}"
